version: '3.8'

services:
  web:
    container_name: latest-news
    image: latest-news
    build: .
    ports:
      - 80:80
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/default.base.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
    env_file:
      - .env.apikey
