version: '3.8'

services:
  web:
    container_name: latest-news
    image: latest-news
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
    env_file:
      - .apikey.env
