const FILTERS_DATA = {
    country: {
        "Argentina": "ar",
        "Australia": "au",
        "Austria": "at",
        "Bangladesh": "bd",
        "Belgium": "be",
        "Brazil": "br",
        "Bulgaria": "bg",
        "Canada": "ca",
        "China": "cn",
        "Colombia": "co",
        "Cuba": "cu",
        "Czech republic": "cz",
        "Egypt": "eg",
        "France": "fr",
        "Germany": "de",
        "Greece": "gr",
        "Hong kong": "hk",
        "Hungary": "hu",
        "India": "in",
        "Indonesia": "id",
        "Iraq": "iq",
        "Ireland": "ie",
        "Israel": "il",
        "Italy": "it",
        "Japan": "jp",
        "Kazakhstan": "kz",
        "Latvia": "lv",
        "Lebanon": "lb",
        "Lithuania": "lt",
        "Malaysia": "my",
        "Mexico": "mx",
        "Morocco": "ma",
        "Netherland": "nl",
        "New zealand": "nz",
        "Nigeria": "ng",
        "North korea": "kp",
        "Norway": "no",
        "Pakistan": "pk",
        "Peru": "pe",
        "Philippines": "ph",
        "Poland": "pl",
        "Portugal": "pt",
        "Romania": "ro",
        "Russia": "ru",
        "Saudi arabia": "sa",
        "Serbia": "rs",
        "Singapore": "sg",
        "Slovakia": "sk",
        "Slovenia": "si",
        "South africa": "za",
        "South korea": "kr",
        "Spain": "es",
        "Sweden": "se",
        "Switzerland": "ch",
        "Taiwan": "tw",
        "Thailand": "th",
        "Turkey": "tr",
        "Ukraine": "ua",
        "United arab emirates": "ae",
        "United kingdom": "gb",
        "United states of america": "us",
        "Venezuela": "ve",
    },
    category: {
        "business": "business",
        "entertainment": "entertainment",
        "environment": "environment",
        "food": "food",
        "health": "health",
        "politics": "politics",
        "science": "science",
        "sports": "sports",
        "technology": "technology",
        "top": "top",
        "world": "world",
    },    
    language: {
        "Arabic": "ar",
        "Bengali": "bn",
        "Bosnian": "bs",
        "Bulgarian": "bg",
        "Central Kurdish": "ckb",
        "Chinese": "zh",
        "Croatian": "hr",
        "Czech": "cs",
        "Dutch": "nl",
        "English": "en",
        "French": "fr",
        "German": "de",
        "Greek": "el",
        "Hebrew": "he",
        "Hindi": "hi",
        "Hungarian": "hu",
        "Indonesian": "in",
        "Italian": "it",
        "Japanese": "jp",
        "Korean": "ko",
        "Latvian": "lv",
        "Lithuanian": "lt",
        "Malay": "ms",
        "Norwegian": "no",
        "Polish": "pl",
        "Portuguese": "pt",
        "Romanian": "ro",
        "Russian": "ru",
        "Serbian": "sr",
        "Slovak": "sk",
        "Slovenian": "sl",
        "Spanish": "es",
        "Swedish": "sv",
        "Thai": "th",
        "Turkish": "tr",
        "Ukrainian": "u",
    },
};

export default FILTERS_DATA;