const FILTERS_DATA = {
  country: {
    argentina: "ar",
    australia: "au",
    austria: "at",
    bangladesh: "bd",
    belgium: "be",
    brazil: "br",
    bulgaria: "bg",
    canada: "ca",
    china: "cn",
    colombia: "co",
    cuba: "cu",
    "czech republic": "cz",
    egypt: "eg",
    france: "fr",
    germany: "de",
    greece: "gr",
    "hong kong": "hk",
    hungary: "hu",
    india: "in",
    indonesia: "id",
    iraq: "iq",
    ireland: "ie",
    israel: "il",
    italy: "it",
    japan: "jp",
    kazakhstan: "kz",
    latvia: "lv",
    lebanon: "lb",
    lithuania: "lt",
    malaysia: "my",
    mexico: "mx",
    morocco: "ma",
    netherland: "nl",
    "new zealand": "nz",
    nigeria: "ng",
    "north korea": "kp",
    norway: "no",
    pakistan: "pk",
    peru: "pe",
    philippines: "ph",
    poland: "pl",
    portugal: "pt",
    romania: "ro",
    russia: "ru",
    "saudi arabia": "sa",
    serbia: "rs",
    singapore: "sg",
    slovakia: "sk",
    slovenia: "si",
    "south africa": "za",
    "south korea": "kr",
    spain: "es",
    sweden: "se",
    switzerland: "ch",
    taiwan: "tw",
    thailand: "th",
    turkey: "tr",
    ukraine: "ua",
    "united arab emirates": "ae",
    "united kingdom": "gb",
    "united states of america": "us",
    venezuela: "ve",
  },
  category: {
    business: "business",
    entertainment: "entertainment",
    environment: "environment",
    food: "food",
    health: "health",
    politics: "politics",
    science: "science",
    sports: "sports",
    technology: "technology",
    top: "top",
    world: "world",
  },
  language: {
    arabic: "ar",
    bengali: "bn",
    bosnian: "bs",
    bulgarian: "bg",
    "central kurdish": "ckb",
    chinese: "zh",
    croatian: "hr",
    czech: "cs",
    dutch: "nl",
    english: "en",
    french: "fr",
    german: "de",
    greek: "el",
    hebrew: "he",
    hindi: "hi",
    hungarian: "hu",
    indonesian: "in",
    italian: "it",
    japanese: "jp",
    korean: "ko",
    latvian: "lv",
    lithuanian: "lt",
    malay: "ms",
    norwegian: "no",
    polish: "pl",
    portuguese: "pt",
    romanian: "ro",
    russian: "ru",
    serbian: "sr",
    slovak: "sk",
    slovenian: "sl",
    spanish: "es",
    swedish: "sv",
    thai: "th",
    turkish: "tr",
    ukrainian: "u",
  },
};

export default FILTERS_DATA;
